export enum PermissionGroup {
  manageAccess = 'manageAccess',
  players = 'players',
  configurations = 'configurations',
  promo = 'promo',
  playerData = 'playerData',
  balances = 'balances',
  playerCommunication = 'playerCommunication',
  notes = 'notes',
  games = 'games',
  gamesCategories = 'gamesCategories',
  gamesProducers = 'gamesProducers',
  staticPages = 'staticPages',
}
export enum PermissionType {
  BackofficGroups = 'backoffice-groups',
  BackofficeUsers = 'backoffice-users',
  BackofficeUsersControl = 'backoffice-users-control',
  BackofficeGamesCategories = 'backoffice-games-categories',
  BackofficeGamesCategoriesSeo = 'backoffice-games-categories-seo',
  BackofficeGamesCategoriesReport = 'backoffice-games-categories-report',
  BackofficeGames = 'backoffice-games',
  BackofficeGamesSeo = 'backoffice-games-seo',
  BackofficeGamesReport = 'backoffice-games-report',
  BackofficeGamesProducers = 'backoffice-games-producers',
  BackofficeGamesProducersSeo = 'backoffice-games-producers-seo',
  BackofficeGamesProducersReport = 'backoffice-games-producers-report',
  SectionSupportService = 'section-support-service',
  BackofficeProjects = 'backoffice-projects',
  BackofficeBanners = 'backoffice-banners',
  BackofficeStaticPages = 'backoffice-static-pages',
  BackofficeStaticPagesSeo = 'backoffice-static-pages-seo',
  BackofficeStaticPagesReport = 'backoffice-static-pages-report',
  FieldPlayerMain = 'field-player-main',
  FieldPlayerStatus = 'field-player-status',
  FieldPlayerIsblocked = 'field-player-isblocked',
  FieldPlayerVerification = 'field-player-verification',
  FieldPlayerManager = 'field-player-manager',
  FieldPlayerAutopayment = 'field-player-autopayment',
  BackofficeNotes = 'backoffice-notes',
  BackofficeNotificationsSms = 'backoffice-notifications-sms',
  BackofficeNotificationsWeb = 'backoffice-notifications-web',
  FieldReadBalance = 'field-read-balance',
  BackofficeRealBalanceUpdate = 'backoffice-real-balance-update',
  BackofficePlayerPaymentSystem = 'backoffice-player-payment-system',
  MarbellaCards = 'marbella-cards',
  BackofficePaymentDailylimits = 'backoffice-payment-dailylimits',
  BackofficeTransactions = 'backoffice-transactions',
  BackofficePlayersBonus = 'backoffice-players-bonus',
  BackofficePlayerGifts = 'backoffice-player-gifts',
  BackofficePaymentBalanceslog = 'backoffice-payment-balanceslog',
  BettingHistory = 'backoffice-betting-history',
  Multiaccounts = 'backoffice-player-multiaccounts',
  BackofficeLogaction = 'backoffice-logaction',
  TreasuryTransactionsChecks = 'backoffice-treasury-transactions-checks',

  AlaroUsers = 'alaro-users',
  AlaroGroups = 'alaro-groups',

  AlaroDistributors = 'alaro-distributors',
  AlaroDistributorsReport = 'alaro-distributors-report',

  AlaroConnections = 'alaro-connections',
  AlaroConnectionsReport = 'alaro-connections-report',

  AlaroOrganizations = 'alaro-organizations',
  AlaroOrganizationsReport = 'alaro-organizations-report',

  AlaroBrands = 'alaro-brands',
  AlaroBrandsReport = 'alaro-brands-report',

  AlaroGames = 'alaro-games',
  AlaroGamesReport = 'alaro-games-report',

  AlaroReportsGame = 'alaro-reports-gameactivity',
  AlaroReportsGameActivityReport = 'alaro-reports-gameactivity-report',

  AlaroReportsRoundHistory = 'alaro-reports-roundhistory',
  AlaroReportsRoundHistoryReport = 'alaro-reports-roundhistory-report',

  AlaroReportsBonuses = 'alaro-reports-bonuses',
  AlaroReportsBonusesReports = 'alaro-reports-bonuses-report',
}
