export enum Location {
  Top = 'top',
  Bottom = 'bottom',
  Center = 'center',
  Start = 'start',
  End = 'end',
  Left = 'left',
  Right = 'right',
  CenterCenter = 'center center',
  TopStart = 'top start',
  TopEnd = 'top end',
  TopLeft = 'top left',
  TopRight = 'top right',
  BottomStart = 'bottom start',
  BottomEnd = 'bottom end',
  BottomLeft = 'bottom left',
  BottomRight = 'bottom right',
  StartCenter = 'start center',
  EndCenter = 'end center',
  LeftCenter = 'left center',
  RightCenter = 'right center',
}
