include:
  - project: common/gitlab-ci-templates
    file: '/build/docker-build-1.0.0.yaml'
    ref: master
  - project: common/gitlab-ci-templates
    file: "/changelog/generate-changelog-1.0.0.yaml"
    ref: master

stages:
  - docker-build
  - docker-push

default:
  tags:
    - ${CI_PROJECT_ROOT_NAMESPACE}-staging

docker-build:
  extends: .docker-build
  variables:
    DOCKERFILE_PATH: './Dockerfile'

docker-push-do:
  extends: .docker-push-do
  only:
    refs:
      - develop
      - master

generate-changelog-with-master:
  extends: .generate-changelog-with-master
  stage: docker-push
generate-changelog-with-before-sha:
  extends: .generate-changelog-with-before-sha
  stage: docker-push

