/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

/// <reference types="unplugin-vue-router/client" />

import type {
  // type safe route locations
  RouteLocationTypedList,
  RouteLocationResolvedTypedList,
  RouteLocationNormalizedTypedList,
  RouteLocationNormalizedLoadedTypedList,
  RouteLocationAsString,
  RouteLocationAsRelativeTypedList,
  RouteLocationAsPathTypedList,

  // helper types
  // route definitions
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,

  // vue-router extensions
  _RouterTyped,
  RouterLinkTyped,
  RouterLinkPropsTyped,
  NavigationGuard,
  UseLinkFnTyped,

  // data fetching
  _DataLoader,
  _DefineLoaderOptions,
} from 'unplugin-vue-router/types'

declare module 'vue-router/auto/routes' {
  export interface RouteNamedMap {
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'access-control': RouteRecordInfo<'access-control', '/access-control', Record<never, never>, Record<never, never>>,
    'actions-miles': RouteRecordInfo<'actions-miles', '/actions/miles', Record<never, never>, Record<never, never>>,
    'actions-promo': RouteRecordInfo<'actions-promo', '/actions/promo', Record<never, never>, Record<never, never>>,
    'analytics-dashboard': RouteRecordInfo<'analytics-dashboard', '/analytics/dashboard', Record<never, never>, Record<never, never>>,
    'analytics-financial-statistics': RouteRecordInfo<'analytics-financial-statistics', '/analytics/financial-statistics', Record<never, never>, Record<never, never>>,
    'auth-logs': RouteRecordInfo<'auth-logs', '/auth-logs', Record<never, never>, Record<never, never>>,
    'authentication-auth-provider': RouteRecordInfo<'authentication-auth-provider', '/authentication/AuthProvider', Record<never, never>, Record<never, never>>,
    'cashbox-cohorts': RouteRecordInfo<'cashbox-cohorts', '/cashbox/cohorts', Record<never, never>, Record<never, never>>,
    'cashbox-sum-ranges': RouteRecordInfo<'cashbox-sum-ranges', '/cashbox/sum-ranges', Record<never, never>, Record<never, never>>,
    'constructor': RouteRecordInfo<'constructor', '/constructor', Record<never, never>, Record<never, never>>,
    'constructor-components-constructor-panel': RouteRecordInfo<'constructor-components-constructor-panel', '/constructor/_components/ConstructorPanel', Record<never, never>, Record<never, never>>,
    'constructor-components-field-card': RouteRecordInfo<'constructor-components-field-card', '/constructor/_components/FieldCard', Record<never, never>, Record<never, never>>,
    'constructor-components-field-card-dynamic-config-inputs': RouteRecordInfo<'constructor-components-field-card-dynamic-config-inputs', '/constructor/_components/FieldCard/DynamicConfigInputs', Record<never, never>, Record<never, never>>,
    'constructor-components-field-card-field-info-block': RouteRecordInfo<'constructor-components-field-card-field-info-block', '/constructor/_components/FieldCard/FieldInfoBlock', Record<never, never>, Record<never, never>>,
    'constructor-components-field-card-i18n-checkboxes': RouteRecordInfo<'constructor-components-field-card-i18n-checkboxes', '/constructor/_components/FieldCard/I18nCheckboxes', Record<never, never>, Record<never, never>>,
    'constructor-components-field-card-raw-toggle': RouteRecordInfo<'constructor-components-field-card-raw-toggle', '/constructor/_components/FieldCard/RawToggle', Record<never, never>, Record<never, never>>,
    'constructor-components-field-card-validation-rules-editor': RouteRecordInfo<'constructor-components-field-card-validation-rules-editor', '/constructor/_components/FieldCard/ValidationRulesEditor', Record<never, never>, Record<never, never>>,
    'constructor-components-flex-mode-blocks': RouteRecordInfo<'constructor-components-flex-mode-blocks', '/constructor/_components/FlexModeBlocks', Record<never, never>, Record<never, never>>,
    'constructor-components-i18n-json-generator': RouteRecordInfo<'constructor-components-i18n-json-generator', '/constructor/_components/I18nJsonGenerator', Record<never, never>, Record<never, never>>,
    'constructor-components-i18n-prefix-editor': RouteRecordInfo<'constructor-components-i18n-prefix-editor', '/constructor/_components/I18nPrefixEditor', Record<never, never>, Record<never, never>>,
    'constructor-components-order-blocks': RouteRecordInfo<'constructor-components-order-blocks', '/constructor/_components/OrderBlocks', Record<never, never>, Record<never, never>>,
    'constructor-components-validation-rules-editor': RouteRecordInfo<'constructor-components-validation-rules-editor', '/constructor/_components/ValidationRulesEditor', Record<never, never>, Record<never, never>>,
    'constructor-components-view-mode-selector': RouteRecordInfo<'constructor-components-view-mode-selector', '/constructor/_components/ViewModeSelector', Record<never, never>, Record<never, never>>,
    'error404': RouteRecordInfo<'error404', '/error/404', Record<never, never>, Record<never, never>>,
    'forgot-password': RouteRecordInfo<'forgot-password', '/forgot-password', Record<never, never>, Record<never, never>>,
    'games-categories': RouteRecordInfo<'games-categories', '/games/categories', Record<never, never>, Record<never, never>>,
    'games-list': RouteRecordInfo<'games-list', '/games/list', Record<never, never>, Record<never, never>>,
    'gamification-achievements': RouteRecordInfo<'gamification-achievements', '/gamification/achievements', Record<never, never>, Record<never, never>>,
    'gamification-levels': RouteRecordInfo<'gamification-levels', '/gamification/levels', Record<never, never>, Record<never, never>>,
    'gifts-cashbacks': RouteRecordInfo<'gifts-cashbacks', '/gifts/cashbacks', Record<never, never>, Record<never, never>>,
    'gifts-list': RouteRecordInfo<'gifts-list', '/gifts/list', Record<never, never>, Record<never, never>>,
    'groups-list': RouteRecordInfo<'groups-list', '/groups/list', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'logs-list': RouteRecordInfo<'logs-list', '/logs/list', Record<never, never>, Record<never, never>>,
    'logs-password-change': RouteRecordInfo<'logs-password-change', '/logs/password-change', Record<never, never>, Record<never, never>>,
    'malaga-attempts': RouteRecordInfo<'malaga-attempts', '/malaga/attempts', Record<never, never>, Record<never, never>>,
    'malaga-channels': RouteRecordInfo<'malaga-channels', '/malaga/channels', Record<never, never>, Record<never, never>>,
    'malaga-clients': RouteRecordInfo<'malaga-clients', '/malaga/clients', Record<never, never>, Record<never, never>>,
    'malaga-integrations': RouteRecordInfo<'malaga-integrations', '/malaga/integrations', Record<never, never>, Record<never, never>>,
    'malaga-notifications': RouteRecordInfo<'malaga-notifications', '/malaga/notifications', Record<never, never>, Record<never, never>>,
    'malaga-templates': RouteRecordInfo<'malaga-templates', '/malaga/templates', Record<never, never>, Record<never, never>>,
    'not-authorized': RouteRecordInfo<'not-authorized', '/not-authorized', Record<never, never>, Record<never, never>>,
    'payouts-fin-managers-statistic': RouteRecordInfo<'payouts-fin-managers-statistic', '/payouts/fin-managers-statistic', Record<never, never>, Record<never, never>>,
    'payouts-list': RouteRecordInfo<'payouts-list', '/payouts/list', Record<never, never>, Record<never, never>>,
    'payouts-rules': RouteRecordInfo<'payouts-rules', '/payouts/rules', Record<never, never>, Record<never, never>>,
    'players-list': RouteRecordInfo<'players-list', '/players/list', Record<never, never>, Record<never, never>>,
    'players-support-service': RouteRecordInfo<'players-support-service', '/players/support-service', Record<never, never>, Record<never, never>>,
    'projects-list': RouteRecordInfo<'projects-list', '/projects/list', Record<never, never>, Record<never, never>>,
    'promo-banners': RouteRecordInfo<'promo-banners', '/promo/banners', Record<never, never>, Record<never, never>>,
    'promo-notifications': RouteRecordInfo<'promo-notifications', '/promo/notifications', Record<never, never>, Record<never, never>>,
    'register': RouteRecordInfo<'register', '/register', Record<never, never>, Record<never, never>>,
    'seo-meta': RouteRecordInfo<'seo-meta', '/seo/meta', Record<never, never>, Record<never, never>>,
    'seo-redirects': RouteRecordInfo<'seo-redirects', '/seo/redirects', Record<never, never>, Record<never, never>>,
    'settings-feature-flags': RouteRecordInfo<'settings-feature-flags', '/settings/feature-flags', Record<never, never>, Record<never, never>>,
    'settings-tags': RouteRecordInfo<'settings-tags', '/settings/tags', Record<never, never>, Record<never, never>>,
    'storybook': RouteRecordInfo<'storybook', '/storybook', Record<never, never>, Record<never, never>>,
    'tournaments-list': RouteRecordInfo<'tournaments-list', '/tournaments/list', Record<never, never>, Record<never, never>>,
    'tournaments-templates': RouteRecordInfo<'tournaments-templates', '/tournaments/templates', Record<never, never>, Record<never, never>>,
    'users-list': RouteRecordInfo<'users-list', '/users/list', Record<never, never>, Record<never, never>>,
    'valdemoro-config': RouteRecordInfo<'valdemoro-config', '/valdemoro/config', Record<never, never>, Record<never, never>>,
    'valdemoro-list': RouteRecordInfo<'valdemoro-list', '/valdemoro/list', Record<never, never>, Record<never, never>>,
  }
}

declare module 'vue-router/auto' {
  import type { RouteNamedMap } from 'vue-router/auto/routes'

  export type RouterTyped = _RouterTyped<RouteNamedMap>

  /**
   * Type safe version of `RouteLocationNormalized` (the type of `to` and `from` in navigation guards).
   * Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationNormalized<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationNormalizedTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocationNormalizedLoaded` (the return type of `useRoute()`).
   * Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationNormalizedLoaded<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocationResolved` (the returned route of `router.resolve()`).
   * Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationResolved<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationResolvedTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocation` . Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocation<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocationRaw` . Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationRaw<Name extends keyof RouteNamedMap = keyof RouteNamedMap> =
    | RouteLocationAsString<RouteNamedMap>
    | RouteLocationAsRelativeTypedList<RouteNamedMap>[Name]
    | RouteLocationAsPathTypedList<RouteNamedMap>[Name]

  /**
   * Generate a type safe params for a route location. Requires the name of the route to be passed as a generic.
   */
  export type RouteParams<Name extends keyof RouteNamedMap> = RouteNamedMap[Name]['params']
  /**
   * Generate a type safe raw params for a route location. Requires the name of the route to be passed as a generic.
   */
  export type RouteParamsRaw<Name extends keyof RouteNamedMap> = RouteNamedMap[Name]['paramsRaw']

  export function useRouter(): RouterTyped
  export function useRoute<Name extends keyof RouteNamedMap = keyof RouteNamedMap>(name?: Name): RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[Name]

  export const useLink: UseLinkFnTyped<RouteNamedMap>

  export function onBeforeRouteLeave(guard: NavigationGuard<RouteNamedMap>): void
  export function onBeforeRouteUpdate(guard: NavigationGuard<RouteNamedMap>): void

  export const RouterLink: RouterLinkTyped<RouteNamedMap>
  export const RouterLinkProps: RouterLinkPropsTyped<RouteNamedMap>

  // Experimental Data Fetching

  export function defineLoader<
    P extends Promise<any>,
    Name extends keyof RouteNamedMap = keyof RouteNamedMap,
    isLazy extends boolean = false,
  >(
    name: Name,
    loader: (route: RouteLocationNormalizedLoaded<Name>) => P,
    options?: _DefineLoaderOptions<isLazy>,
  ): _DataLoader<Awaited<P>, isLazy>
  export function defineLoader<
    P extends Promise<any>,
    isLazy extends boolean = false,
  >(
    loader: (route: RouteLocationNormalizedLoaded) => P,
    options?: _DefineLoaderOptions<isLazy>,
  ): _DataLoader<Awaited<P>, isLazy>

  export {
    _definePage as definePage,
    _HasDataLoaderMeta as HasDataLoaderMeta,
    _setupDataFetchingGuard as setupDataFetchingGuard,
    _stopDataFetchingScope as stopDataFetchingScope,
  } from 'unplugin-vue-router/runtime'
}

declare module 'vue-router' {
  import type { RouteNamedMap } from 'vue-router/auto/routes'

  export interface TypesConfig {
    beforeRouteUpdate: NavigationGuard<RouteNamedMap>
    beforeRouteLeave: NavigationGuard<RouteNamedMap>

    $route: RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[keyof RouteNamedMap]
    $router: _RouterTyped<RouteNamedMap>

    RouterLink: RouterLinkTyped<RouteNamedMap>
  }
}
