---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "ingressHostname" . }}
spec:
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-certs
  secretName: {{ include "ingressHostname" . }}
  dnsNames:
    - {{ include "ingressHostname" . }}
