image:
  name: "<argocd placeholder>"
  tag: "latest"

desc:
  env: ""

dynamic:
  isDynamic: "false"
  branchSlug: ""

## for dynamic envs only
ingress:
  controller:
    name: "nginx"

gateway:
  name: "public-gateway"
  namespace: "nginx-gateway"
  sectionName: "https"
  clientSettings:
    maxBodySize: "10m"

### ingressHostName = ingressHost + ingressDomain
ingressDomain: "boffice.site"
ingressHost: ""
