import type { ThemeDefinition } from 'vuetify'
import { GREY } from './colors'

export const staticPrimaryColor = '#6D60F0'

export const themes: Record<string, ThemeDefinition> = {
  light: {
    dark: false,
    colors: {
      'primary': staticPrimaryColor,
      'primary-300': '#A9A2F6',
      'on-primary': '#fff',
      'secondary': '#787A80',
      'on-secondary': '#fff',
      'success': '#0DB157',
      'on-success': '#fff',
      'info': '#3B83F7',
      'on-info': '#fff',
      'warning': '#F08C35',
      'on-warning': '#fff',
      'error': '#EA3D3E',
      'background': '#F9F9FA',
      'on-background': GREY.light['grey-900'],
      'on-surface': '#2F2B3D',
      'grey-50': GREY.light['grey-50'],
      'grey-100': GREY.light['grey-100'],
      'grey-200': GREY.light['grey-200'],
      'grey-300': GREY.light['grey-300'],
      'grey-400': GREY.light['grey-400'],
      'grey-500': GREY.light['grey-500'],
      'grey-600': GREY.light['grey-600'],
      'grey-700': GREY.light['grey-700'],
      'grey-800': GREY.light['grey-800'],
      'grey-900': GREY.light['grey-900'],
      'body': GREY.light['grey-900'],
      'extra-body': '#F9F9FA',
      'border-color': '#2F2B3D',

      'perfect-scrollbar-thumb': '#DBDADE',
      'skin-bordered-background': '#fff',
      'skin-bordered-surface': '#fff',
    },

    variables: {
      'table-bg': '#EFEFF0',
      'code-color': '#d400ff',
      'overlay-scrim-background': '#4C4E64',
      'tooltip-background': GREY.light['grey-800'],
      'overlay-scrim-opacity': 0.5,
      'hover-opacity': 0.04,
      'focus-opacity': 0.12,
      'selected-opacity': 0.06,
      'activated-opacity': 0.16,
      'alert-opacity': 0.16,
      'badge-opacity': 0.16,
      'pressed-opacity': 0.14,
      'dragged-opacity': 0.1,
      'disabled-opacity': 0.32,
      'border-opacity': 0.16,
      'high-emphasis-opacity': 0.9,
      'medium-emphasis-opacity': 0.62,
      'opacity-grey': 0.24,
      'switch-opacity': 0.2,
      'switch-disabled-track-opacity': 0.3,
      'switch-disabled-thumb-opacity': 0.4,
      'switch-checked-disabled-opacity': 0.3,
      'muted-placeholder-opacity': 0.62, // TODO: medium-emphasis-opacity
      'body-opacity': 0.9,
      'border-radius': '0.5rem',

      // Shadows
      'shadow-key-umbra-color': '#2F2B3D',

      // Table
      'c-table-head-bg': '#EFEFF0',
    },
  },
  dark: {
    dark: true,
    colors: {
      'primary': staticPrimaryColor,
      'primary-300': '#A9A2F6',
      'on-primary': '#fff',
      'secondary': '#A8AAAE',
      'on-secondary': '#fff',
      'success': '#28C76F',
      'on-success': '#fff',
      'info': '#3B83F7',
      'on-info': '#fff',
      'warning': '#FF9F43',
      'on-warning': '#fff',
      'error': '#EA5455',
      'background': '#25293C',
      'on-background': GREY.dark['grey-900'],
      'surface': '#2F3349',
      'on-surface': '#D0D4F1',

      'grey-50': GREY.dark['grey-50'],
      'grey-100': GREY.dark['grey-100'],
      'grey-200': GREY.dark['grey-200'],
      'grey-300': GREY.dark['grey-300'],
      'grey-400': GREY.dark['grey-400'],
      'grey-500': GREY.dark['grey-500'],
      'grey-600': GREY.dark['grey-600'],
      'grey-700': GREY.dark['grey-700'],
      'grey-800': GREY.dark['grey-800'],
      'grey-900': GREY.dark['grey-900'],

      'perfect-scrollbar-thumb': GREY.dark['grey-300'],
      'skin-bordered-background': '#2F3349',
      'skin-bordered-surface': '#2F3349',
    },
    variables: {
      'table-bg': '#3D4155',
      'code-color': '#d400ff',
      'overlay-scrim-background': '#101121',
      'tooltip-background': GREY.dark['grey-400'],
      'overlay-scrim-opacity': 0.6,
      'hover-opacity': 0.04,
      'focus-opacity': 0.12,
      'selected-opacity': 0.06,
      'activated-opacity': 0.16,
      'pressed-opacity': 0.14,
      'dragged-opacity': 0.1,
      'disabled-opacity': 0.32,
      'border-color': '#D0D4F1',
      'border-opacity': 0.16,
      'high-emphasis-opacity': 0.78,
      'medium-emphasis-opacity': 0.68,
      'switch-opacity': 0.4,
      'switch-disabled-track-opacity': 0.4,
      'switch-disabled-thumb-opacity': 0.8,
      'switch-checked-disabled-opacity': 0.3,
      'border-radius': '0.5rem',

      // Shadows
      'shadow-key-umbra-color': '#0F1422',

      // Table
      'c-table-head-bg': '#242532',
    },
  },
}

export default themes
