export enum Strategy {
  AUTHORIZED = 'AUTHORIZED',
  DEPOSIT_COUNT_IN_RANGE = 'DEPOSIT_COUNT_IN_RANGE',
  FIRST_DEPOSIT = 'FIRST_DEPOSIT',
  GUEST = 'GUEST',
  LEVEL_IN_RANGE = 'LEVEL_IN_RANGE',
  REFCODE = 'REFCODE',
  SHOW_ALWAYS = 'SHOW_ALWAYS',
}
