name: Deploy
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - OlehMiha-patch-1

jobs:
  deploy-core-service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "latest"
          cache: "npm"

      - name: Unit Tests and build
        run: npm run build-cf

      - name: Check Formatting
        run: npm run check

      - name: Deploy app
        uses: cloudflare/wrangler-action@v3
        with:
          workingDirectory: "./server/dist"
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy --env ${{ github.event.inputs.environment }}


