name: Deploy
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - OlehMiha-patch-1

jobs:
  deploy-core-service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "latest"
          cache: "npm"

      - name: Install yarn
        run: npm i -g yarn

      - name: Yarn install
        run: yarn install

      - name: Unit Tests
        run: npm run test:unit

      - name: Build
        run: npm run build-cf

      - name: Deploy app
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: '3a-9nGHjLVUrB53bqn4YyTek8J6W0rp-S3xdlC2C'
          accountId: '820a6538083a7f942dd27ff462d4e35c'
          command: pages deploy ./server/dist --project-name=cardona-core-service

      - name: Print deployment-url
        env:
          DEPLOYMENT_URL: ${{ steps.deploy.outputs.deployment-url }}
        run: echo $DEPLOYMENT_URL


