name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    environment: production

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Install @octokit/auth-app
        run: yarn add @octokit/auth-app

      - name: Debug environment variables
        run: echo "🔹 REPO_URL=${{ github.server_url }}/${{ github.repository }}"

      - name: Get GitHub App Token
        id: app_token
        run: |
          echo "${{ secrets.GH_APP_PRIVATE_KEY }}" > private-key.pem
          TOKEN=$(node <<EOF
          const { createAppAuth } = require("@octokit/auth-app");
          const { readFileSync } = require("fs");
          (async () => {
            const auth = createAppAuth({
              appId: "${{ secrets.GH_APP_ID }}",
              privateKey: readFileSync("private-key.pem", "utf8"),
              installationId: "${{ secrets.GH_INSTALLATION_ID }}"
            });
            const installationAuthentication = await auth({ type: "installation" });
            console.log(installationAuthentication.token);
          })();
          EOF
          )
          echo "::add-mask::$TOKEN"
          echo "GITHUB_TOKEN=$TOKEN" >> $GITHUB_ENV

      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          REPO_URL: "${{ github.server_url }}/${{ github.repository }}"
        run: npx semantic-release

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore(release): auto release [skip ci]"
          branch: auto-release-pr
          base: master
          title: "Automated Release PR"
          body: "This PR contains an automated release from semantic-release."
